
import { createLogger } from 'logger.js';
import { fsScope } from 'gateway.js';
import 'upstream/shims/npm-bridges.js';
const log = createLogger('v6');
const root = await fsScope.resolve();
globalThis.__dshProfileScopeRoot = root.path;
globalThis.__dshProfileCwd = root.path;
const { registerWordTools } = await import('system-plugins/dsh-office/word.js');
const { registerExcelTools } = await import('system-plugins/dsh-office/excel.js');
const { registerPptCreate } = await import('system-plugins/dsh-office/ppt-create.js');
const [wc] = registerWordTools();
const [ec] = registerExcelTools();
const [pc] = registerPptCreate();
globalThis.__dshComplete(false, 'M-reg');
await wc.execute({ path: 'val.docx', title: 'D', paragraphs: ['x'], bullets: ['b'], table: { headers: ['H'], rows: [['r']] } });
globalThis.__dshComplete(false, 'M-word');
const ex = await ec.execute({ path: 'val.xlsx', sheets: [{ name: 'S1', rows: [['Name', 'N'], ['x', 7]] }] });
globalThis.__dshComplete(false, 'M-excel');
await pc.execute({ path: 'val.pptx', title: 'Deck', slides: [{ title: 'S', bullets: ['p'], notes: 'n' }] });
globalThis.__dshComplete(false, 'M-ppt');
