import { createLogger } from 'logger.js';
import { fsScope } from 'gateway.js';
import 'upstream/shims/npm-bridges.js';
const log = createLogger('val');
const root = await fsScope.resolve();
globalThis.__dshProfileScopeRoot = root.path;
globalThis.__dshProfileCwd = root.path;
log.info('val', { step: 'root', path: root.path });
const { registerWordTools } = await import('system-plugins/dsh-office/word.js');
const { registerExcelTools } = await import('system-plugins/dsh-office/excel.js');
log.info('val', { step: 'imports-1' });
const { registerPptCreate } = await import('system-plugins/dsh-office/ppt-create.js');
log.info('val', { step: 'imports-2' });
const [wc] = registerWordTools();
log.info('val', { step: 'reg-word' });
const [ec] = registerExcelTools();
log.info('val', { step: 'reg-excel' });
const [pc] = registerPptCreate();
log.info('val', { step: 'registered' });
await wc.execute({ path: 'val.docx', title: 'Validation Doc', paragraphs: ['Body one.', 'Body two.'], bullets: ['b1', 'b2'], table: { headers: ['H1', 'H2'], rows: [['a', 'b'], ['c', 'd']] } });
log.info('val', { step: 'docx-done' });
const ex = await ec.execute({ path: 'val.xlsx', sheets: [{ name: 'S1', rows: [['Name', 'N', 'Flag'], ['x', 7, true], ['y', 2.5, false]] }] });
log.info('val', { step: 'xlsx-done', rows: ex.sheets[0].rowCount });
await pc.execute({ path: 'val.pptx', title: 'Validation Deck', slides: [{ title: 'Slide A', bullets: ['p1', 'p2'], notes: 'note text' }] });
log.info('val', { step: 'pptx-done', root: root.path });
