// dsh:logging-exempt (node-side generator: console IS the product)
/**
 * gen.mjs — the theme token single source, rendered to its two faces.
 *
 * tokens.json is the ONLY place a color/radius/gradient value is defined
 * (theme = data; the chat→theme.json ladder plugs in here later). This
 * script emits:
 *   - web.tokens.css          — the web face (CSS custom properties, the
 *                               `:root` vocabulary of web-client-next's
 *                               theme.css, dark-first with a light block)
 *   - ../bundle/src/theme.generated.ts — the Lynx face (typed style
 *                               constants the ReactLynx components import)
 *
 * `node theme/gen.mjs` writes both; `node theme/gen.mjs --check` re-runs
 * the render in memory and exits 1 naming any drifted file (the gateable
 * form — never hand-edit either generated file).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));

const read = () => JSON.parse(readFileSync(join(HERE, 'tokens.json'), 'utf8'));

const kebab = (key) => key
  .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
  .replace(/([A-Z])([A-Z][a-z])/g, '$1-$2')
  .toLowerCase();

/** The flat scalar face of one mode: brand + semantic + aurora + gradient
 * + the mode's adaptive block (radius is numeric and rendered per-face). */
const flatten = (doc, mode) => {
  const { brand, semantic, aurora, gradient, adaptive } = doc.tokens;
  return { ...brand, ...semantic, ...aurora, ...gradient, ...adaptive[mode] };
};

const webFace = (doc) => {
  const block = (mode) => {
    const flat = flatten(doc, mode);
    const lines = Object.entries(flat).map(([key, value]) =>
      `  --${kebab(key)}: ${value};`);
    const radius = Object.entries(doc.tokens.radius)
      .map(([key, value]) => `  --r-${kebab(key)}: ${value}px;`);
    return [...lines, ...radius].join('\n');
  };
  return `/* GENERATED by theme/gen.mjs from tokens.json — do not hand-edit.
 * The web face of the token single source (the :root vocabulary of
 * web-client-next's theme.css, dark-first). Regenerate: node theme/gen.mjs */
:root {
${block('dark')}
}

@media (prefers-color-scheme: light) {
  :root {
${block('light')}
  }
}
`;
};

const lynxFace = (doc) => {
  const flat = flatten(doc, 'dark');
  const lines = Object.entries(flat).map(([key, value]) =>
    `  ${key}: ${JSON.stringify(value)},`);
  const radius = Object.entries(doc.tokens.radius)
    .map(([key, value]) => `  ${key}: ${value},`)
    .join('\n');
  const gradients = Object.entries(doc.tokens.gradient)
    .map(([key, value]) => `  ${key}: ${JSON.stringify(value)},`)
    .join('\n');
  return `// GENERATED by theme/gen.mjs from tokens.json — do not hand-edit.
// The Lynx face of the token single source: typed style constants the
// ReactLynx components import (dark pilot face; light values live in
// tokens.json for the chat→theme.json ladder). Regenerate: node theme/gen.mjs

export const theme = {
${lines.join('\n')}
} as const;

export const radius = {
${radius}
} as const;

export const gradient = {
${gradients}
} as const;

export type Theme = typeof theme;
`;
};

const targets = [
  { path: join(HERE, 'web.tokens.css'), render: webFace, label: 'theme/web.tokens.css' },
  {
    path: join(HERE, '../bundle/src/theme.generated.ts'),
    render: lynxFace,
    label: 'bundle/src/theme.generated.ts',
  },
];

const tokens = read();
const check = process.argv.includes('--check');
let drifted = 0;
for (const target of targets) {
  const rendered = target.render(tokens);
  if (check) {
    let current = '';
    try { current = readFileSync(target.path, 'utf8'); } catch { /* missing = drift */ }
    if (current !== rendered) {
      console.error(`theme drift: ${target.label} is not in sync with tokens.json`);
      drifted += 1;
    }
  } else {
    writeFileSync(target.path, rendered);
    console.log(`theme: wrote ${target.label}`);
  }
}
if (check) {
  if (drifted > 0) {
    console.error(`theme: ${drifted} generated file(s) drifted — run node theme/gen.mjs`);
    process.exit(1);
  }
  console.log('theme: both faces in sync with tokens.json');
}
