package com.dshmobile.spike

import java.io.File
import java.io.OutputStream
import java.security.MessageDigest

/**
 * The `/plugins` prefix route — the client-modules bundle surface of
 * docs/webserver-contract.md §2.5, generated by the carrier from the staged
 * plugin set (§3.4: same JSON/URL shapes upstream emits, no upstream code).
 * Serves the revisioned single-resource combo `/plugins/??<id>/client.js
 * &rev=<rev>`, the aggregate `/plugins/??<a>/client.js,<b>/client.js&rev=…`
 * combine form, and the `.map` identity maps; anything else under /plugins
 * is an unknown resource → 404; non-GET/HEAD → 405. Kotlin sibling of
 * hosts/ios CarrierPlugins.swift (package-local chunks stay off the boot
 * path and are not staged on Android — a chunk fetch 404s, upstream's own
 * stale-rev behavior).
 */
class CarrierPlugins private constructor(bundles: List<Pair<String, File>>) {

    /** One staged bundle, prepared once at init (upstream `prepareSource`). */
    class Prepared(val id: String, val source: String) {
        var rev: String = shortHash(source)
    }

    /** Staged entries in boot-graph order (deterministic; not a dictionary). */
    private val entries = ArrayList<Prepared>()
    private val byId = HashMap<String, Prepared>()

    init {
        for ((id, file) in bundles) {
            val raw = try {
                file.readText(Charsets.UTF_8)
            } catch (_: Exception) {
                continue
            }
            val entry = Prepared(id, prepareSource(raw))
            entries.add(entry)
            byId[id] = entry
        }
    }

    /** Evidence hook: (resource URL, byte count) per served bundle. */
    var onComboServed: ((String, Int) -> Unit)? = null

    /** The prefix handler to register on the carrier server. */
    val handler: (CarrierRequest, OutputStream) -> Unit = { request, out -> serve(request, out) }

    /** The boot-graph rows this plugin set yields (upstream `WebBootEntry`):
     * one revisioned single-resource combo URL per entry, graph order =
     * registration order of `bundles`. */
    fun bootEntries(): List<Map<String, String>> = entries.map {
        mapOf("id" to it.id, "url" to entryURL(it.id, it.rev), "rev" to it.rev)
    }

    /** Adopts the RUNTIME's graph rows (`web.boot`): the upstream composer's
     * initial revisions are per-boot placeholders (nonce-counter), so the
     * /plugins route must serve and validate against the runtime's revs,
     * not the carrier's content hashes. Rows whose id matches a staged
     * entry override its rev; unknown ids are ignored (the carrier serves
     * only what it stages — fail loud upstream if the graph disagrees). */
    fun applyRuntimeRevs(rows: List<Map<String, Any>>) {
        synchronized(this) {
            for (row in rows) {
                val id = row["id"] as? String ?: continue
                val rev = row["rev"] as? String ?: continue
                byId[id]?.let { it.rev = rev }
            }
        }
    }

    // ---- request handling -------------------------------------------------------

    private fun serve(request: CarrierRequest, out: OutputStream) {
        if (request.method != "GET" && request.method != "HEAD") {
            return respond(out, 405, ByteArray(0), "text/plain")
        }
        if (request.rawPath == "/plugins" || request.rawPath == "/plugins/") {
            return serveCombo(request, out)
        }
        serveSingle(request, out)
    }

    /** The combine form: `??<id>/client.js(,<id>/client.js)*&rev=<rev>`
     * (upstream `buildComboScript`: each prepared source is followed by
     * `;\n`, then the combo's own sourceMappingURL line). The `??` form's
     * second `?` rides in the stored query (everything after the first). */
    private fun serveCombo(request: CarrierRequest, out: OutputStream) {
        val query = request.query?.removePrefix("?")
        val body = query?.let { parseComboQuery(it)?.let { (resources, rev) -> comboBody(resources, rev) } }
        if (query == null || body == null) {
            return respond(out, 404, ByteArray(0), "text/plain")
        }
        onComboServed?.invoke("/plugins/??$query", body.utf8Count())
        respond(out, 200, body.toByteArray(Charsets.UTF_8), SCRIPT_MIME)
    }

    /** Single-resource forms: `/plugins/<id>/client.js?rev=` (a one-entry
     * combo) and `/plugins/<id>/client.js.map?rev=` (identity map). */
    private fun serveSingle(request: CarrierRequest, out: OutputStream) {
        val path = request.path ?: return respond(out, 400, ByteArray(0), "text/plain")
        val pieces = path.split("/").filter { it.isNotEmpty() }
        if (pieces.size != 3 || pieces[0] != "plugins") {
            return respond(out, 404, ByteArray(0), "text/plain")
        }
        val entry = synchronized(this) { byId[pieces[1]] }
            ?: return respond(out, 404, ByteArray(0), "text/plain")
        if (request.query != "rev=${synchronized(this) { entry.rev }}") {
            return respond(out, 404, ByteArray(0), "text/plain")
        }
        when (pieces[2]) {
            "client.js" -> {
                val rev = synchronized(this) { entry.rev }
                val mapURL = "/plugins/??${entry.id}/client.js.map&rev=$rev"
                val body = entry.source + ";\n//# sourceMappingURL=$mapURL\n"
                onComboServed?.invoke("/plugins/??${entry.id}/client.js&rev=$rev", body.utf8Count())
                respond(out, 200, body.toByteArray(Charsets.UTF_8), SCRIPT_MIME)
            }
            "client.js.map" -> {
                val map = identityMap(
                    entry.source, "/plugins/${entry.id}/client.js",
                )
                respond(out, 200, map.toByteArray(Charsets.UTF_8), MAP_MIME)
            }
            else -> respond(out, 404, ByteArray(0), "text/plain")
        }
    }

    private fun respond(out: OutputStream, status: Int, body: ByteArray, mime: String) {
        val headers = if (status == 200) mapOf("Cache-Control" to CACHE_CONTROL) else emptyMap()
        CarrierHTTP.respond(out, status, mime, body, headers = headers)
    }

    // ---- combo semantics (upstream helpers, carrier-generated) --------------------

    /** Splits `resources&rev=<rev>`; nil-shaped queries return null (404). */
    private fun parseComboQuery(query: String): Pair<List<String>, String>? {
        val at = query.indexOf("&rev=")
        if (at < 0) return null
        val resources = query.substring(0, at)
        val rev = query.substring(at + "&rev=".length)
        val ids = resources.split(",").filter { it.isNotEmpty() }
        if (ids.isEmpty()) return null
        return ids to rev
    }

    /** Builds the combo body when every listed `<id>/client.js` is staged and
     * the declared rev matches the ordered combo rev; null otherwise (404). */
    private fun comboBody(resources: List<String>, rev: String): String? {
        if (resources.any { !it.endsWith("/client.js") }) return null
        val ids = resources.map { it.removeSuffix("/client.js") }
        val resolved = synchronized(this) { ids.map { byId[it] } }
        if (resolved.any { it == null }) return null
        val revs = resolved.map { it!!.rev }
        val comboRev = comboRev(ids, revs)
        if (comboRev != rev) return null
        var body = ""
        for (entry in resolved.filterNotNull()) body += entry.source + ";\n"
        val mapResources = ids.map { "$it/client.js.map" }.joinToString(",")
        body += "//# sourceMappingURL=/plugins/??$mapResources&rev=$comboRev\n"
        return body
    }

    companion object {
        const val CACHE_CONTROL = "public, max-age=31536000, immutable"
        const val SCRIPT_MIME = "text/javascript; charset=utf-8"
        const val MAP_MIME = "application/json; charset=utf-8"

        /** The /plugins route over the STAGED plugin set (the route's fallback
         * rows while the runtime boots): the full staged web-plugin tree
         * (web-plugins — the W-SHELL application tier, 58 `dsh.client`
         * packages). The runtime's `web.boot` replaces the rows + revs before
         * the origin opens; the route must serve every staged package the
         * composed graph lists (sorted directory order = the delivery order =
         * the graph's scan-order tie-break). */
        fun staged(webPluginsRoot: File): CarrierPlugins {
            val scope = File(webPluginsRoot, "npm/@deepseek-ai")
            val bundles = ArrayList<Pair<String, File>>()
            for (pkg in scope.listFiles()?.filter { it.isDirectory }?.sortedBy { it.name } ?: emptyList()) {
                val at = pkg.name.lastIndexOf('@')
                if (at <= 0) continue
                bundles.add("@deepseek-ai/" + pkg.name.substring(0, at) to File(pkg, "lib/client.js"))
            }
            return CarrierPlugins(bundles)
        }

        /** Boot-graph entry URL: the revisioned single-resource combo form. */
        fun entryURL(id: String, rev: String) = "/plugins/??$id/client.js&rev=$rev"

        /** Strips bundle-local debug trailers and keeps a trailing newline
         * (upstream `prepareSource`). */
        fun prepareSource(raw: String): String {
            val lines = raw.split("\n").toMutableList()
            while (lines.isNotEmpty()) {
                val last = lines.last()
                val trimmed = if (last.endsWith("\r")) last.dropLast(1) else last
                if (trimmed.startsWith("//# sourceMappingURL=") ||
                    trimmed.startsWith("//# sourceURL=")
                ) {
                    lines.removeAt(lines.size - 1)
                    if (lines.isEmpty()) break
                    continue
                }
                break
            }
            var source = lines.joinToString("\n")
            if (source.isNotEmpty() && !source.endsWith("\n")) source += "\n"
            return source
        }

        /** sha1 content hash shortened to 12 hex chars (upstream `shortHash`). */
        fun shortHash(input: String) = sha1_12(input.toByteArray(Charsets.UTF_8))

        /** Upstream `framedHash`: length-prefixed parts so bytes cannot move
         * across field boundaries. */
        fun comboRev(ids: List<String>, revs: List<String>): String {
            val data = java.io.ByteArrayOutputStream()
            data.write("combo\u0000".toByteArray(Charsets.UTF_8))
            for ((id, rev) in ids.zip(revs)) {
                data.write("${id.toByteArray(Charsets.UTF_8).size}:".toByteArray(Charsets.UTF_8))
                data.write(id.toByteArray(Charsets.UTF_8))
                data.write("${rev.toByteArray(Charsets.UTF_8).size}:".toByteArray(Charsets.UTF_8))
                data.write(rev.toByteArray(Charsets.UTF_8))
            }
            return sha1_12(data.toByteArray())
        }

        /** Identity per-line map for one generated source (upstream
         * `identitySectionMap`), wrapped in the combo indexed-map form. */
        fun identityMap(source: String, sourceURL: String, file: String = "client.js"): String {
            val lines = source.split("\n").size
            val mappings = (0 until maxOf(lines, 1)).joinToString(";") { if (it == 0) "AAAA" else "AACA" }
            val section = mapOf(
                "version" to 3, "names" to emptyList<String>(), "sources" to listOf(sourceURL),
                "sourcesContent" to listOf(source), "mappings" to mappings,
            )
            val wrapped = mapOf(
                "version" to 3, "file" to file,
                "sections" to listOf(mapOf("offset" to mapOf("line" to 0, "column" to 0), "map" to section)),
            )
            val json = org.json.JSONObject(wrapped).toString()
                .replace("<", "\\u003c")
            return "$json\n"
        }

        fun sha1_12(data: ByteArray): String {
            val digest = MessageDigest.getInstance("SHA-1").digest(data)
            return digest.joinToString("") { "%02x".format(it) }.take(12).lowercase()
        }

        private fun String.utf8Count() = toByteArray(Charsets.UTF_8).size
    }
}
