#!/usr/bin/env python3
"""Embed the runtime/spike JS bundle into the iOS app as C byte arrays.

The spike host loads ESM imports (logger.js, the vendored dsh package) from
disk under a bundle_root. Compiling the JS into the binary and staging it to
a writable sandbox directory at launch keeps the app free of asset-path
resolution: the bytes the simulator runs are byte-identical to the checkout.

Outputs are committed (App/Generated/) so a fresh clone builds without this
script; the Xcode pre-build phase re-runs it whenever an input changes.
"""

from pathlib import Path

HOSTS_IOS = Path(__file__).resolve().parents[1]
REPO = HOSTS_IOS.parents[1]
SPIKE = REPO / "runtime" / "spike"
OUT = HOSTS_IOS / "App" / "Generated"
GUARD = "DSH_IOS_SPIKE_BUNDLE_H"

# (accessor suffix, source file) -> dsh_spike_res_<suffix>()
RESOURCES = [
    ("logger_js", SPIKE / "logger.js"),
    ("gateway_js", SPIKE / "gateway.js"),
    ("registry_js", SPIKE / "registry.js"),
    ("manifest_json", SPIKE / "manifest.json"),
    ("scenario_js", SPIKE / "scenario" / "m1-spike-boot.js"),
    ("scenario_m2_js", SPIKE / "scenario" / "m2-gateway-binding.js"),
    ("scenario_m2_smoke_js", SPIKE / "scenario" / "m2-bridge-smoke.js"),
    ("scenario_m2_session_js", SPIKE / "scenario" / "m2-session.js"),
    ("scenario_carrier_js", SPIKE / "scenario" / "m1-carrier-loopback.js"),
    ("web_index_html", SPIKE / "web" / "index.html"),
    ("web_page_js", SPIKE / "web" / "carrier-page.js"),
    ("pkg_crypto_js",
     SPIKE / "vendor" / "dsh" / "util-crypto@0.1.6-alpha.1" / "lib" / "index.js"),
    # system implementation plugins (repo-root tree, staged bundle-relative
    # under system-plugins/ — the scenario's canonical import specifier)
    ("plugin_fs_manifest", REPO / "system-plugins" / "dsh-fs" / "manifest.json"),
    ("plugin_fs_js", REPO / "system-plugins" / "dsh-fs" / "index.js"),
    ("plugin_subprocess_manifest",
     REPO / "system-plugins" / "dsh-subprocess-quickjs" / "manifest.json"),
    ("plugin_subprocess_js",
     REPO / "system-plugins" / "dsh-subprocess-quickjs" / "index.js"),
    ("plugin_ui_manifest", REPO / "system-plugins" / "dsh-ui" / "manifest.json"),
    ("plugin_ui_js", REPO / "system-plugins" / "dsh-ui" / "index.js"),
    # the active Web Client plugin (presentation/, type=web-client, web/ dir)
    ("webclient_manifest", REPO / "presentation" / "web-client" / "manifest.json"),
    ("webclient_index_html", REPO / "presentation" / "web-client" / "web" / "index.html"),
    ("webclient_main_js", REPO / "presentation" / "web-client" / "web" / "main.js"),
]


def c_array(symbol: str, data: bytes, raw: bytes) -> str:
    if b"\x00" in raw:
        raise SystemExit(f"gen_bundle_header: {symbol} contains a NUL byte")
    rows = []
    for at in range(0, len(raw), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in raw[at:at + 16])
        rows.append(f"  {chunk},")
    body = "\n".join(rows)
    # trailing NUL keeps the array a valid C string (dsh_spike_eval strlens)
    return f"static const unsigned char {symbol}[] = {{\n{body}\n  0x00\n}};\n"


def emit() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    parts, decls, funcs = [], [], []
    for suffix, path in RESOURCES:
        if not path.is_file():
            raise SystemExit(f"gen_bundle_header: missing input {path}")
        symbol = f"DSH_{suffix.upper()}"
        raw = path.read_bytes()
        data = raw + b"\x00"
        parts.append(f"/* {path.relative_to(REPO)} ({len(data) - 1} bytes) */\n{c_array(symbol, data, raw)}")
        decls.append(f"const char *dsh_spike_res_{suffix}(size_t *len);")
        funcs.append(
            f"const char *dsh_spike_res_{suffix}(size_t *len) {{\n"
            f"  if (len) *len = sizeof({symbol}) - 1;\n"
            f"  return (const char *){symbol};\n"
            f"}}\n"
        )

    header = "\n".join([
        "/* Generated by hosts/ios/Tools/gen_bundle_header.py — do not edit.",
        " * Re-embeds the runtime/spike JS bundle (byte arrays, NUL-terminated). */",
        f"#ifndef {GUARD}",
        f"#define {GUARD}",
        "",
        "#include <stddef.h>",
        "",
        *decls,
        "",
        f"#endif /* {GUARD} */",
        "",
    ])
    source = "\n".join([
        "/* Generated by hosts/ios/Tools/gen_bundle_header.py — do not edit. */",
        '#include "SpikeBundle.h"',
        "",
        *parts,
        *funcs,
    ])
    (OUT / "SpikeBundle.h").write_text(header, encoding="utf-8")
    (OUT / "SpikeBundle.c").write_text(source, encoding="utf-8")
    print(f"gen_bundle_header: wrote {OUT / 'SpikeBundle.c'} + .h")


if __name__ == "__main__":
    emit()
