#!/usr/bin/env python3
"""The embedded-tree C section emitters for gen_bundle_header.py — split out
to keep both files under the code-size gate. One tree = per-file byte arrays
addressed by a single index accessor the Swift stager walks."""

from pathlib import Path


def c_array(symbol: str, data: bytes, raw: bytes) -> str:
    rows = []
    for at in range(0, len(raw), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in raw[at:at + 16])
        rows.append(f"  {chunk},")
    body = "\n".join(rows)
    return f"static const unsigned char {symbol}[] = {{\n{body}\n  0x00\n}};\n"


def tree_c_source(tree: list, prefix: str, accessor: str, repo: Path) -> str:
    """One embedded tree as a C section: per-file arrays addressed by a
    single index accessor (the Swift stager walks it without N decls).
    Comments carry REPO-RELATIVE paths — an absolute path would make the
    generated bytes machine-dependent (the drift the closures gate exists
    to catch)."""
    tree_arrays, tree_paths, tree_lens = [], [], []
    for i, (rel, path) in enumerate(tree):
        if not Path(path).is_file():
            raise SystemExit(f"gen_bundle_header: missing tree input {path}")
        symbol = f"{prefix}_TREE_{i:03d}"
        raw = Path(path).read_bytes()
        if b"\x00" in raw:
            raise SystemExit(f"gen_bundle_header: {rel} contains a NUL byte")
        shown = Path(path).relative_to(repo)
        tree_arrays.append(
            f"/* {shown} ({len(raw)} bytes) */\n{c_array(symbol, raw, raw)}")
        tree_paths.append(f'  "{rel}",')
        tree_lens.append(f"  sizeof({symbol}) - 1,")
    data_idx_rows = "\n".join(
        f"  {prefix}_TREE_{i:03d}," for i in range(len(tree)))
    head = [
        f"/* ---- the {accessor} tree section ---- */\n",
        "\n".join(tree_arrays),
        f"\nstatic const char *const {prefix}_TREE_PATHS[] = {{\n",
        "\n".join(tree_paths),
        f"\n}};\n\nstatic const unsigned char *const {prefix}_TREE_DATA[] = {{\n",
        data_idx_rows,
        f"\n}};\n\nstatic const size_t {prefix}_TREE_LENS[] = {{\n",
        "\n".join(tree_lens),
        "\n};\n\n",
    ]
    walker = [
        f"int {accessor}(size_t index, const char **path,\n",
        "  const char **data, size_t *len) {\n",
        f"  if (index >= {len(tree)}) return 0;\n",
        f"  if (path) *path = {prefix}_TREE_PATHS[index];\n",
        f"  if (data) *data = {prefix}_TREE_DATA[index];\n",
        f"  if (len) *len = {prefix}_TREE_LENS[index];\n",
        "  return 1;\n",
        "}\n",
    ]
    return "".join(head) + "".join(walker)


def tree_walker_decl(comment: str, accessor: str) -> str:
    return (f"/* {comment}\n"
            f" * fills path/data/len for `index`, returns 0 past the end. */\n"
            f"int {accessor}(size_t index, const char **path,\n"
            f" const char **data, size_t *len);")


SPINE_TREE_WALKER_DECL = tree_walker_decl(
    "The staged tree walker (vendored spine packages + zod closure):",
    "dsh_spike_bundle_tree_file")
WEBCLIENT_TREE_WALKER_DECL = tree_walker_decl(
    "The self-hosted web client tree walker (presentation/web-client-next):",
    "dsh_spike_webclient_tree_file")
