import CryptoKit
import Foundation
import Network

/// The `/plugins` prefix route — the client-modules bundle surface of
/// docs/webserver-contract.md §2.5, generated by the carrier from the staged
/// plugin set (§3.4: same JSON/URL shapes upstream emits, no upstream code).
/// Serves the revisioned single-resource combo `/plugins/??<id>/client.js
/// &rev=<rev>`, the aggregate `/plugins/??<a>/client.js,<b>/client.js&rev=…`
/// combine form, and the `.map` identity maps; anything else under /plugins
/// is an unknown resource → 404; non-GET/HEAD → 405.
final class CarrierPlugins {
    /// Evidence hook: (resource URL, byte count) per served bundle.
    var onComboServed: ((String, Int) -> Void)?
    static let cacheControl = "public, max-age=31536000, immutable"
    static let scriptMIME = "text/javascript; charset=utf-8"
    static let mapMIME = "application/json; charset=utf-8"

    /// One staged bundle, prepared once at init (upstream `prepareSource`).
    struct Prepared {
        let id: String
        let source: String
        let rev: String
    }

    /// Staged entries in boot-graph order (deterministic; not a dictionary).
    private(set) var entries: [Prepared] = []
    private var byId: [String: Prepared] = [:]

    /// - Parameter bundles: plugin id → its `client.js` file on disk, in the
    ///   order the boot graph should list them.
    init(bundles: [(String, URL)]) {
        for (id, url) in bundles {
            guard let raw = try? String(contentsOf: url, encoding: .utf8) else { continue }
            let source = Self.prepareSource(raw)
            let entry = Prepared(id: id, source: source, rev: Self.shortHash(source))
            entries.append(entry)
            byId[id] = entry
        }
    }

    /// The prefix handler to register on the carrier server.
    var handler: CarrierHTTPHandler { { [weak self] request, conn in
        self?.serve(request, conn: conn)
    } }

    /// The boot-graph rows this plugin set yields (upstream `WebBootEntry`):
    /// one revisioned single-resource combo URL per entry, graph order =
    /// registration order of `bundles`.
    func bootEntries() -> [[String: String]] {
        entries.map { ["id": $0.id, "url": Self.entryURL(id: $0.id, rev: $0.rev), "rev": $0.rev] }
    }

    // ---- request handling -------------------------------------------------------

    private func serve(_ request: CarrierRequest, conn: NWConnection) {
        guard request.method == "GET" || request.method == "HEAD" else {
            return respond(405, body: Data(), mime: "text/plain", request: request, conn: conn)
        }
        if request.query?.hasPrefix("?") == true,
           request.rawPath == "/plugins" || request.rawPath == "/plugins/" {
            return serveCombo(request, conn: conn)
        }
        serveSingle(request, conn: conn)
    }

    /// The combine form: `??<id>/client.js(,<id>/client.js)*&rev=<rev>`
    /// (upstream `buildComboScript`: each prepared source is followed by
    /// `;\n`, then the combo's own sourceMappingURL line).
    private func serveCombo(_ request: CarrierRequest, conn: NWConnection) {
        let query = String(request.query?.dropFirst() ?? "")
        guard let (resources, rev) = parseComboQuery(query),
              let body = comboBody(resources, rev: rev) else {
            return respond(404, body: Data(), mime: "text/plain", request: request, conn: conn)
        }
        onComboServed?("/plugins/?" + "?" + query, body.utf8.count)
        respond(200, body: Data(body.utf8), mime: Self.scriptMIME,
                request: request, conn: conn)
    }

    /// Single-resource forms: `/plugins/<id>/client.js?rev=` (a one-entry
    /// combo) and `/plugins/<id>/client.js.map?rev=` (identity map).
    private func serveSingle(_ request: CarrierRequest, conn: NWConnection) {
        guard let path = request.path else {
            return respond(400, body: Data(), mime: "text/plain", request: request, conn: conn)
        }
        let pieces = path.split(separator: "/").map(String.init)
        guard pieces.count == 3, pieces[0] == "plugins" else {
            return respond(404, body: Data(), mime: "text/plain", request: request, conn: conn)
        }
        guard let entry = byId[pieces[1]] else {
            return respond(404, body: Data(), mime: "text/plain", request: request, conn: conn)
        }
        guard request.query == "rev=\(entry.rev)" else {
            return respond(404, body: Data(), mime: "text/plain", request: request, conn: conn)
        }
        serveKnown(pieces[2], entry: entry, request: request, conn: conn)
    }

    private func serveKnown(
        _ fileName: String, entry: Prepared, request: CarrierRequest, conn: NWConnection
    ) {
        switch fileName {
        case "client.js":
            serveEntryScript(entry, request: request, conn: conn)
        case "client.js.map":
            let map = Self.identityMap(source: entry.source, sourceURL: "/plugins/\(entry.id)/client.js")
            respond(200, body: Data(map.utf8), mime: Self.mapMIME, request: request, conn: conn)
        default:
            respond(404, body: Data(), mime: "text/plain", request: request, conn: conn)
        }
    }

    /// The one-entry combo body for a staged bundle: prepared source, the
    /// `;\n` terminator, and the combo sourceMappingURL trailer.
    private func serveEntryScript(
        _ entry: Prepared, request: CarrierRequest, conn: NWConnection
    ) {
        let mapURL = "/plugins/??\(entry.id)/client.js.map&rev=\(entry.rev)"
        let body = entry.source + ";\n//# sourceMappingURL=\(mapURL)\n"
        onComboServed?("/plugins/??\(entry.id)/client.js&rev=\(entry.rev)", body.utf8.count)
        respond(200, body: Data(body.utf8), mime: Self.scriptMIME,
                request: request, conn: conn)
    }

    private func respond(
        _ status: Int, body: Data, mime: String,
        request: CarrierRequest, conn: NWConnection
    ) {
        var response = "HTTP/1.1 \(status) \(Self.reason(status))\r\n"
        response += "Content-Type: \(mime)\r\nContent-Length: \(body.count)\r\n"
        if status == 200 { response += "Cache-Control: \(Self.cacheControl)\r\n" }
        response += "Connection: close\r\n\r\n"
        var payload = Data(response.utf8)
        if request.method != "HEAD" { payload.append(body) }
        conn.send(content: payload, completion: .contentProcessed { _ in conn.cancel() })
    }

    private static func reason(_ status: Int) -> String {
        switch status {
        case 200: return "OK"
        case 404: return "Not Found"
        case 405: return "Method Not Allowed"
        default: return "Error"
        }
    }

    // ---- combo semantics (upstream helpers, carrier-generated) --------------------

    private func parseComboQuery(_ query: String) -> ([String], String)? {
        guard let at = query.range(of: "&rev=") else { return nil }
        let resources = String(query[..<at.lowerBound])
        let rev = String(query[at.upperBound...])
        let ids = resources.split(separator: ",").map(String.init)
        guard !ids.isEmpty else { return nil }
        return (ids, rev)
    }

    /// Builds the combo body when every listed `<id>/client.js` is staged and
    /// the declared rev matches the ordered combo rev; nil otherwise (404).
    private func comboBody(_ resources: [String], rev: String) -> String? {
        var ids: [String] = []
        for resource in resources {
            guard resource.hasSuffix("/client.js") else { return nil }
            ids.append(String(resource.dropLast("/client.js".count)))
        }
        let resolved = ids.map { byId[$0] }
        guard resolved.allSatisfy({ $0 != nil }) else { return nil }
        let comboRev = Self.comboRev(ids: ids, revs: resolved.map { $0!.rev })
        guard comboRev == rev else { return nil }
        var body = ""
        for entry in resolved.compactMap({ $0 }) { body += entry.source + ";\n" }
        let mapResources = ids.map { "\($0)/client.js.map" }.joined(separator: ",")
        body += "//# sourceMappingURL=/plugins/??\(mapResources)&rev=\(comboRev)\n"
        return body
    }

    /// Boot-graph entry URL: the revisioned single-resource combo form.
    static func entryURL(id: String, rev: String) -> String {
        "/plugins/??\(id)/client.js&rev=\(rev)"
    }

    // ---- upstream byte semantics ----------------------------------------------------

    /// Strips bundle-local debug trailers and keeps a trailing newline
    /// (upstream `prepareSource`).
    static func prepareSource(_ raw: String) -> String {
        var lines = raw.components(separatedBy: "\n")
        while let last = lines.last {
            let trimmed = last.hasSuffix("\r") ? String(last.dropLast()) : last
            if trimmed.hasPrefix("//# sourceMappingURL=") || trimmed.hasPrefix("//# sourceURL=") {
                lines.removeLast()
                if lines.isEmpty { break }
                continue
            }
            break
        }
        var source = lines.joined(separator: "\n")
        if !source.isEmpty && !source.hasSuffix("\n") { source += "\n" }
        return source
    }

    /// sha1 content hash shortened to 12 hex chars (upstream `shortHash`).
    static func shortHash(_ input: String) -> String {
        sha1_12(Data(input.utf8))
    }

    /// Upstream `framedHash`: length-prefixed parts so bytes cannot move
    /// across field boundaries.
    static func comboRev(ids: [String], revs: [String]) -> String {
        var data = Data("combo\0".utf8)
        for (id, rev) in zip(ids, revs) {
            data.append(Data("\(id.utf8.count):".utf8))
            data.append(Data(id.utf8))
            data.append(Data("\(rev.utf8.count):".utf8))
            data.append(Data(rev.utf8))
        }
        return sha1_12(data)
    }

    /// Identity per-line map for one generated source (upstream
    /// `identitySectionMap`), wrapped in the combo indexed-map form.
    static func identityMap(source: String, sourceURL: String) -> String {
        let lines = source.split(separator: "\n", omittingEmptySubsequences: false).count
        let mappings = (0..<max(lines, 1)).map { $0 == 0 ? "AAAA" : "AACA" }
            .joined(separator: ";")
        let section: [String: Any] = [
            "version": 3, "names": [String](), "sources": [sourceURL],
            "sourcesContent": [source], "mappings": mappings,
        ]
        let wrapped: [String: Any] = [
            "version": 3, "file": "client.js",
            "sections": [["offset": ["line": 0, "column": 0], "map": section]],
        ]
        guard let data = try? JSONSerialization.data(withJSONObject: wrapped),
              var json = String(data: data, encoding: .utf8) else { return "{}" }
        json = json.replacingOccurrences(of: "<", with: "\\u003c")
        return json + "\n"
    }

    static func sha1_12(_ data: Data) -> String {
        let digest = Insecure.SHA1.hash(data: data)
        return digest.map { String(format: "%02x", $0) }.joined().prefix(12).lowercased()
    }
}
