#!/usr/bin/env python3
"""Regenerate runtime/spike/scenario/agent-presets-probe-seed.js.

The presets seed the CLI probe (and any scenario that mounts the REAL
AgentPresets service) delivers over the bus: the vendored presets tree bytes
plus one node_modules resolution marker per vendored dsh package. The device
drives (iOS WebBootRuntimeDrive.agentPresetsSeedDelivery, and the staged
Android/Harmony equivalents) synthesize the SAME marker rule from their
staged trees — this script is the reproducible CLI twin.

Marker rule (agent-presets health resolution walks
  <preset-pkg>/node_modules/@deepseek-ai/<name>/package.json):
  {"name": "<pkg name>", "version": "<pkg version>",
   "_spike": "resolution marker (the bare map vendors this package)"}
A preset row naming a package WITHOUT a marker stays honestly `broken` —
markers are generated from the vendored closure only, never speculatively.

usage: gen-presets-seed.py   (writes the .js file; run from anywhere)
"""

import base64
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
SPIKE = REPO / "runtime" / "spike"
VENDOR = SPIKE / "vendor" / "dsh"
PRESETS_PKG = "agent-presets"
OUT = SPIKE / "scenario" / "agent-presets-probe-seed.js"
VFS_BASE = f"/vendor/dsh/{PRESETS_PKG}@"
MARKER_SPIKE = "resolution marker (the bare map vendors this package)"


def collect_files() -> dict[str, str]:
    """The seed's {vfs_path: base64} map: presets tree + resolution markers."""
    pkg_dirs = sorted(
        (d for d in VENDOR.iterdir() if d.is_dir() and "@0." in d.name),
        key=lambda d: d.name,
    )
    if not pkg_dirs:
        print(f"gen-presets-seed: no vendored packages under {VENDOR}", file=sys.stderr)
        sys.exit(1)
    files: dict[str, str] = {}
    files.update(presets_tree())
    files.update(marker_entries(pkg_dirs))
    return files


def presets_tree() -> dict[str, str]:
    presets_root = VENDOR / f"{PRESETS_PKG}@0.1.6-alpha.2" / "presets"
    if not presets_root.is_dir():
        print(f"gen-presets-seed: missing {presets_root}", file=sys.stderr)
        sys.exit(1)
    out: dict[str, str] = {}
    for path in sorted(presets_root.rglob("*")):
        if path.is_file():
            rel = path.relative_to(presets_root)
            vfs = f"{VFS_BASE}0.1.6-alpha.2/presets/{rel}"
            out[vfs] = base64.b64encode(path.read_bytes()).decode()
    return out


def marker_entries(pkg_dirs) -> dict[str, str]:
    """One resolution marker per vendored package (name+version from its own
    package.json — never assumed)."""
    out: dict[str, str] = {}
    for d in pkg_dirs:
        manifest = json.loads((d / "package.json").read_text(encoding='utf-8'))
        marker = {
            "name": manifest["name"], "version": manifest["version"],
            "_spike": MARKER_SPIKE,
        }
        vfs = f"{VFS_BASE}0.1.6-alpha.2/node_modules/{manifest['name']}/package.json"
        out[vfs] = base64.b64encode(
            json.dumps(marker, ensure_ascii=False).encode()
        ).decode()
    return out


def main() -> int:
    files = collect_files()
    markers = sum(1 for k in files if "/node_modules/" in k)

    # 3. Emit the module: a default-exported {vfsPath: {bytes, mtimeMs}} map.
    lines = [
        "// GENERATED by runtime/spike/ci/gen-presets-seed.py — presets tree",
        "// (bytes) + node_modules resolution markers, one per vendored dsh",
        "// package. Regenerate after every ensure-dsh.sh re-pin; the device",
        "// drives synthesize the same rule from their staged trees.",
        "const files = {",
    ]
    for vfs in sorted(files):
        payload = ",".join(str(b) for b in base64.b64decode(files[vfs]))
        lines.append(f'  "{vfs}": {{ bytes: new Uint8Array([{payload}]), mtimeMs: 0 }},')
    lines += ["};", "export default files;"]
    OUT.write_text("\n".join(lines) + "\n", encoding='utf-8')
    print(f"gen-presets-seed: {len(files)} files ({markers} markers) -> {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
