// GENERATED by theme/gen.mjs from tokens.json — do not hand-edit.
// The Lynx face of the token single source: typed style constants the
// ReactLynx components import (dark pilot face; light values live in
// tokens.json for the chat→theme.json ladder). Regenerate: node theme/gen.mjs

export const theme = {
  navy: "#06172B",
  navyRaised: "#0B2440",
  ocean: "#2E6BE6",
  oceanBright: "#6FB3FF",
  oceanDeep: "#1554C2",
  oceanGlow: "#0E3A6E",
  oceanHaze: "#123C77",
  mist: "#BFD6FF",
  ink: "#0E131A",
  paper: "#F9FAFC",
  purple: "#7A54C7",
  orange: "#F07D14",
  amber: "#FFAD1F",
  green: "#2EB85C",
  red: "#E5484D",
  blobOcean: "rgba(46, 107, 230, 0.25)",
  blobHaze: "rgba(18, 60, 119, 0.55)",
  blobPurple: "rgba(122, 84, 199, 0.18)",
  send: "linear-gradient(135deg, #2E6BE6, #6FB3FF)",
  sendPressed: "linear-gradient(135deg, rgba(46, 107, 230, 0.92), rgba(21, 84, 194, 0.88))",
  bg: "#0B0F14",
  bgRaised: "#11161D",
  text: "#E8ECF2",
  text2: "#9AA4B2",
  text3: "#6B7686",
  line: "rgba(191, 214, 255, 0.12)",
  fill: "rgba(191, 214, 255, 0.08)",
  glassBg: "rgba(11, 36, 64, 0.55)",
  glassStroke: "rgba(191, 214, 255, 0.22)",
  userBubble: "rgba(46, 107, 230, 0.24)",
  userBubbleLine: "rgba(46, 107, 230, 0.42)",
} as const;

export const radius = {
  composer: 24,
  menu: 22,
  card: 18,
  bubble: 15,
  output: 10,
} as const;

export const gradient = {
  send: "linear-gradient(135deg, #2E6BE6, #6FB3FF)",
  sendPressed: "linear-gradient(135deg, rgba(46, 107, 230, 0.92), rgba(21, 84, 194, 0.88))",
} as const;

export type Theme = typeof theme;
